### ISSUE TITLE
StreamHandler Produces Extra Empty Lines

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Logging#63]
Output of simpletest run with current main branch:
```
42085.612: INFO - Default handler: Info message

42085.612: ERROR - Stream Handler: Error message

42085.612: ERROR - Test exception handlingTest exception handling
  Traceback (most recent call last):
  
    File "/home/timc/repos/circuitpython/Adafruit_CircuitPython_Logging/examples/logging_simpletest.py", line 29, in <module>
      raise RuntimeError("Test exception handling")
  
  RuntimeError: Test exception handling
  
```

Output of the simpletest run in cpython modified to use `logging` instead of this library:
```
Stream Handler: Error message
Test exception handling
Traceback (most recent call last):
  File "/home/timc/repos/circuitpython/Adafruit_CircuitPython_Logging/examples/logging_simpletest.py", line 29, in <module>
    raise RuntimeError("Test exception handling")
RuntimeError: Test exception handling
```

**Comment by FoamyGuy** [comment]
resolved by #62
